### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by bmovva** [AreYouFreeBusy/AlexaSkillsKit.NET#67]

**Comment by stefann42** [comment]
Please read Override Request Validation Policy https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET#override-request-validation-policy

**Comment by bmovva** [comment]
but i think it only works for v1.0 im using your latest version v1.6

**Comment by stefann42** [comment]
I think you're getting confused. The library feature I mentioned was introduced only in the 1.4 version of the library and is carried through to the current version. Sorry, can't provide any more support. Read more tutorials for Alexa development at http://www.robinosborne.co.uk/2016/12/12/introduction-to-alexa-skills-from-zero-to-echo/ and the how others use this library at https://tutorials.botsfloor.com/having-a-merry-geeky-christmas-creating-an-alexa-skill-with-asp-net-web-api-d4a2cd6d016d

**Comment by ElvenMonky** [comment]
Well, without description it is difficult to understand, what kind of issue you're experiencing. It can be either difficulties with providing SSL certificate for hosted skill, or issues with validation of certificate, or even something else.

**Comment by bmovva** [comment]
thanx @ElvenMonky for your response when i used to use the older version of the code it used to work fine and my skill is live too but when i downlaoded the new version and deployed it .it is not able to verify the signature and othere .below is the attached pic about the errors i get 

at AlexaSkillsKit.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\AsyncHelpers.cs:line 101
   at AlexaSkillsKit.AsyncHelpers.RunSync[T](Func`1 task) in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\AsyncHelpers.cs:line 61
   at AlexaSkillsKit.Speechlet.SpeechletBase.GetResponse(HttpRequestMessage httpRequest) in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletBase.cs:line 0
   at AlexaSkillsKit.myDEP.Controllers.AlexaController.DEPSession() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.myDEP\Speechlet\AlexaController.cs:line 29   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlexaSkillsKit.Authentication.SpeechletRequestSignatureVerifier.
<RetrieveAndVerifyCertificateAsync>d__6.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Authentication\SpeechletRequestSignatureVerifier.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlexaSkillsKit.Authentication.SpeechletRequestSignatureVerifier.
    <VerifyRequestSignatureAsync>d__4.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Authentication\SpeechletRequestSignatureVerifier.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlexaSkillsKit.Speechlet.SpeechletService.
        <GetRequestAsync>d__9.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletService.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlexaSkillsKit.Speechlet.SpeechletService.
            <GetResponseAsync>d__8.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletService.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlexaSkillsKit.Speechlet.SpeechletBase.<>c__DisplayClass4_0.<
                <GetResponse>b__0>d.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletBase.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlexaSkillsKit.AsyncHelpers.<>c__DisplayClass1_0`1.<
                    <RunSync>b__0>d.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\AsyncHelpers.cs:line 54

**Comment by ElvenMonky** [comment]
Ok, I'm reopening an issue as it looks like an issue with syncronous api introduced by recent changes

**Comment by ElvenMonky** [comment]
@bmovva  The stack trace you provided sadly misses the initial part with actual error occured. Could you, please, provide it too

**Comment by bmovva** [comment]
Thankyou @ElvenMonky I hope i gave you all the info now 


It has like 3 levels of exceptions 
1)First level 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlexaSkillsKit.Authentication.SpeechletRequestSignatureVerifier.<RetrieveAndVerifyCertificateAsync>d__6.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Authentication\SpeechletRequestSignatureVerifier.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlexaSkillsKit.Authentication.SpeechletRequestSignatureVerifier.<VerifyRequestSignatureAsync>d__4.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Authentication\SpeechletRequestSignatureVerifier.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlexaSkillsKit.Speechlet.SpeechletService.<GetRequestAsync>d__9.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletService.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlexaSkillsKit.Speechlet.SpeechletService.<GetResponseAsync>d__8.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletService.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlexaSkillsKit.Speechlet.SpeechletBase.<>c__DisplayClass4_0.<<GetResponse>b__0>d.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\Speechlet\SpeechletBase.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AlexaSkillsKit.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext() in D:\AMR\My DEP Alexa\Mian\AlexaSkillsKit.Lib\AsyncHelpers.cs:line 54


second level(inner exception)Message = "Unable to connect to the remote server"

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

third level (Message = "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.216.229.245:443")

   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

**Comment by ElvenMonky** [comment]
Now its clear, thanks. It looks like your certificate URL is unreachable. Where are you hosting your skill?

While it won't help you, library should still handle possible exceptions when trying to connect to certificate URL, rather then throwing. We will discuss it internally.

**Comment by bmovva** [comment]
Actually i selected my development end point has certificate from trusted authority but now i changed it the thing you said but still no luck .Regarding your question 
It is hosted on a staging server

**Comment by ElvenMonky** [comment]
52.216.229.245:443 (from error message) - belongs to [https://aws.amazon.com/s3/](https://aws.amazon.com/s3/) range, and particular ip is not available at the moment. Is that where your staging server hosted? If that's the case, you need to use host name instead of ip address, when configuring your skill's endpoint. Read on: [Amazon S3 Virtual Hosting](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html)

Then you will be able to use Amazons own sertificate by choosing "subdomain" option.

**Comment by bmovva** [comment]
https://a826-web01.xxx.xxx/Alexaservice_Staging/alexa/dep-session

Im using using host name and not any ip address .

**Comment by ElvenMonky** [comment]
@stefann42 I've added error handling when reading certificate from Url to both v1 and master. Now it is treated as certificate validation error, giving developers a chance to ignore it in development and staging environments.

**Comment by bmovva** [comment]
@ElvenMonky i made changes to my code and its working locally without any errors but the response time is far worse its taking more than normal . Im logging all those details in my db .When i make the same request through Alexa it is giving an error because it expects the response within 8 second . let me know if anyone is having this issue so that i can work on my side if no one has this error .
BTW my skill with old version of this code used to work perfectly fine .

**Comment by stefann42** [comment]
@ElvenMonky I think it's great to try to help @bmovva but the fix seems speculative. By which I mean this issue doesn't clearly explain the problem in a reproducible manner so the fix is based on you own logical deduction of what could be happening. I'm not saying there isn't a problem, but IMHO making a speculative fix is worse than no fix. In addition I disagree with catching `Exception` at the layer you have implemented that in your change 

@bmovva with all due respect, I don't understand your setup and your problem description isn't very clear. There are many possible explanations. For ex, it's possible you are having problems making outbound network calls to the Amazon location where the Alexa certificate is posted.

**Comment by stefann42** [comment]
Not sure what your point is. What do you mean by "perform differently"? And what version is the "old library"? Is the synchronous interface even relevant here? That is, do you know for a fact that @bmovva is using the synchronous call stack.  From the call stack in the exception above it seems async interface is being used.

**Comment by ElvenMonky** [comment]
Sorry, for not being clear. In all library versions prior to v1.6.0 Speechlet.GetResponse and SpeechletAsync.GetResponseAsync had similar but different implementations. In v1.6.0 GetResponse uses AsyncHelpers.RunSync to run GetResponseAsync synchronously.
Stack trace provided by @bmovva shows that GetResponse was called. So, I suspect, that issues are caused by this change.

**Comment by ElvenMonky** [comment]
@bmovva can you switch back to v1.5.2 just to make sure, that everything still works as expected with that library version?

**Comment by bmovva** [comment]
@ElvenMonky It works fine with the older versions

**Comment by ElvenMonky** [comment]
@bmovva please, contact me on [mail](mailto://Elvenmonk@mail.ru) so that we can discuss your setup in more details.

**Comment by ElvenMonky** [comment]
It looked really like [this very old issue with ASP.NET SynchronizationContext and `HttpClient.GetAsync()`](https://stackoverflow.com/questions/10343632/httpclient-getasync-never-returns-when-using-await-async), but that's exactly why AsyncHelper was added into library.

I updated tests to emulate ASP.NET SynchronizationContext behavior based on [source code](https://referencesource.microsoft.com/#System.Web/AspNetSynchronizationContext.cs) but still was unable to reproduce an issue.
